"""Added account table

Revision ID: 2fdc9fbcd5c3
Revises: c7f61a20e460
Create Date: 2023-02-28 17:23:52.424571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdc9fbcd5c3'
down_revision = 'c7f61a20e460'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
